### ISSUE TITLE
Credits for siv2r/bitcoin-miner

### ISSUE THREAD

**Issue by siv2r** [shoryak/Summer_of_Bitcoin_code_challenge#1]
I am glad that you find my repository useful. You can at least give credits for the info that you copy-pasted from my repository to your README :disappointed:

**Comment by shoryak** [comment]
Are i am still building it , it will give due credits, If i will use it
, otherwise i will have copyright issues :'(. I apologise again .  

On 2021-07-11 22:09, Sivaram D wrote:

> I am glad that you find my repository useful. You can at least give credits for the info that you copy-pasted from my repository to your README 😞 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/shoryak/Summer_of_Bitcoin_code_challenge/issues/1
[2]

**Comment by siv2r** [comment]
@shoryak Ohh.. Sorry for the misunderstanding. 
All the best!
